# Doesn't work due to the lack of CSRF cookie
### SignUp
POST http://localhost:8000/auth/signup/
Accept: application/x-www-form-urlencoded

username=contritest&password=lmao123

### @name KNAVE
GET http://localhost:8000/knave/character/generate/
Accept: application/json


###
